fix: release workflow condition for existing tag

diff --git a/.github/workflows/publish-release.yaml b/.github/workflows/publish-release.yaml
--- a/.github/workflows/publish-release.yaml
+++ b/.github/workflows/publish-release.yaml
@@ -17,8 +17,11 @@ jobs:
       - name: Create GitHub release
         run: |
           release_tag="v$(yq '.version' ".github/release.yml")"
+
           echo "Check if the release tag: $release_tag already exists ...."
-          if ! git tag --list "$release_tag" >/dev/null 2>&1; then
+
+          ## using test case and substituion because git tag command always returns 0 exit code.
+          if ! [[ "$(git tag --list "$release_tag")" ]] ; then
             echo "Git Tag: $release_tag does not exists, tag and create a new release"
             gh release create "$release_tag" --title  "$release_tag" --draft --generate-notes --latest --repo "${{ github.repository_owner }}/${{ github.event.repository.name }}"
           else
